apiVersion: apps/v1
kind: Deployment
metadata:
  name: forklift-console-plugin
  namespace: konveyor-forklift
  labels:
    app: forklift-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forklift-console-plugin
  template:
    metadata:
      labels:
        app: forklift-console-plugin
    spec:
      containers:
        - name: forklift-console-plugin
          image: localhost:5001/kubev2v/forklift-console-plugin-dev
          stdin: true
          tty: true
          ports:
            - containerPort: 9001
              protocol: TCP
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: forklift-console-plugin
  namespace: konveyor-forklift
  labels:
    app: forklift-console-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: forklift-console-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: forklift-console-plugin-ssh
  namespace: konveyor-forklift
spec:
  ports:
  - name: 22-ssh
    nodePort: 30022
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: forklift-console-plugin
  sessionAffinity: None
  type: NodePort
