apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: forklift-console-plugin-dev
  annotations:
    description: "Forklift console plugin development pod"
objects:

- apiVersion: console.openshift.io/v1alpha1
  kind: ConsolePlugin
  metadata:
    name: forklift-console-plugin
    annotations:
      console.openshift.io/use-i18n: "true"
  spec:
    displayName: 'Console Plugin Forklift'

    service:
      name: forklift-console-plugin
      namespace: ${NAMESPACE}
      port: 9443
      basePath: '/'
    proxy:
      - type: Service
        alias: forklift-must-gather-api
        authorize: true
        service:
          name: forklift-must-gather-api
          namespace: ${NAMESPACE}
          port: 8443
      - type: Service
        alias: forklift-inventory
        authorize: true
        service:
          name: forklift-inventory
          namespace: ${NAMESPACE}
          port: 8443

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: forklift-console-plugin
    namespace: ${NAMESPACE}
    labels:
      app: forklift-console-plugin
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: forklift-console-plugin
    template:
      metadata:
        labels:
          app: forklift-console-plugin
      spec:
        volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        containers:
          - name: forklift-console-plugin
            securityContext:
              privileged: true
            image: ${IMAGE}
            stdin: true
            tty: true
            ports:
              - containerPort: 9443
                protocol: TCP
              - containerPort: 22
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
              - name: plugin-serving-cert
                readOnly: true
                mountPath: /var/serving-cert

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
    name: forklift-console-plugin
    namespace: ${NAMESPACE}
    labels:
      app: forklift-console-plugin
      app.kubernetes.io/component: forklift-console-plugin
      app.kubernetes.io/instance: forklift-console-plugin
      app.kubernetes.io/part-of: forklift-console-plugin
  spec:
    ports:
      - name: 9443-tcp
        protocol: TCP
        port: 9443
        targetPort: 9443
    selector:
      app: forklift-console-plugin
    type: ClusterIP
    sessionAffinity: None

- apiVersion: v1
  kind: Service
  metadata:
    name: forklift-console-plugin-ssh
    namespace: ${NAMESPACE}
  spec:
    ports:
      - name: 22-tcp
        protocol: TCP
        port: 22
        targetPort: 22
        nodePort: 30022
    selector:
      app: forklift-console-plugin
    type: NodePort
    sessionAffinity: None

parameters:
- name: NAMESPACE
  description: Namespace of the forklift operator (konveyor-forklift, openshift-mtv)
  value: konveyor-forklift
- name: IMAGE
  description: Containerized development image to use
  value: quay.io/kubev2v/forklift-console-plugin-dev:latest
