apiVersion: v1
kind: Namespace
metadata:
  name: konveyor-forklift
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minivirt-plugin
  namespace: konveyor-forklift
  labels:
    app: minivirt-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minivirt-plugin
  template:
    metadata:
      labels:
        app: minivirt-plugin
    spec:
      containers:
        - name: minivirt-plugin
          image: quay.io/kubev2v/minivirt-plugin:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: minivirt-plugin
  namespace: konveyor-forklift
  labels:
    app: minivirt-plugin
spec:
  ports:
    - name: 9001-tcp
      protocol: TCP
      port: 9001
      targetPort: 8080
  selector:
    app: minivirt-plugin
  type: ClusterIP
  sessionAffinity: None
