kind: Secret
apiVersion: v1
metadata:
  name: openstack-test
  namespace: konveyor-forklift
data:
  domainName: RGVmYXVsdA==
  insecureSkipVerify: dHJ1ZQ==
  password: MTJlMmYxNDczOTE5NGE2Yw==
  projectName: YWRtaW4=
  regionName: UmVnaW9uT25l
  url: >-
    aHR0cDovL3BhY2tzdGFjay5rb252ZXlvci1mb3JrbGlmdC5zdmMuY2x1c3Rlci5sb2NhbDo1MDAwL3Yz
  username: YWRtaW4=
type: Opaque
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: openstack-test
  namespace: konveyor-forklift
spec:
  secret:
    name: openstack-test
    namespace: konveyor-forklift
  type: openstack
  url: 'http://packstack.konveyor-forklift.svc.cluster.local:5000/v3'
