kind: Secret
apiVersion: v1
metadata:
  name: ovirt-test
  namespace: konveyor-forklift
data:
  cacert: ''
  insecureSkipVerify: dHJ1ZQ==
  password: MTIzNDU2
  url: >-
    aHR0cHM6Ly9mYWtlb3ZpcnQua29udmV5b3ItZm9ya2xpZnQuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMDEvb3ZpcnQtZW5naW5lL2FwaQ==
  user: YWRtaW5AaW50ZXJuYWw=
type: Opaque
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: ovirt-test
  namespace: konveyor-forklift
spec:
  secret:
    name: ovirt-test
    namespace: konveyor-forklift
  type: ovirt
  url: 'https://fakeovirt.konveyor-forklift.svc.cluster.local:30001/ovirt-engine/api'
