apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: forklift-mustgather
spec:
  host: forklift-mustgather-openshift-mtv.apps.mtv.rhev.lab.eng.brq.redhat.com
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: forklift-must-gather-api
    weight: 100
  wildcardPolicy: None