apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: forklift-inventory-serving-cert
  name: forklift-inventory
  namespace: konveyor-forklift
spec:
  ports:
  - name: api-http
    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  sessionAffinity: None
  type: NodePort
