name: Build Helm packgage
on:
  push:
    branches:
      - main
      - release*

jobs:
  build:
    name: Build and publish helm repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure git local user
      run: |
        git config user.name 'forklift_gh_robot'
        git config user.email 'forklift_gh_robot@github.com'

    - name: Build helm package
      # Build the helm package and index.yaml files into
      # the tmp directory then save them in the runner temporary
      # directory so we can copy them to the gh-pages branch.
      run: |
        yarn helm:build
        cp tmp/* ${{ runner.temp }}

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Commit and Push helm package to gh-pages
      # Copy the new helm package and commit it to gh-pages
      # branch.
      run: |
        cp ${{ runner.temp }}/index.yaml ./
        cp ${{ runner.temp }}/forklift-console-plugin-*.tgz ./
        git add ./index.yaml
        git add ./forklift-console-plugin-*.tgz
        git commit -m "Automated helm package"
        git push origin gh-pages
