
name: Test
on:
  pull_request:

jobs:
  tests:
    name: Run linter and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Lint, eslint and stylelint
        run: yarn lint

      - name: Lint, test i18n files and helm
        run: yarn test:i18n

      - name: Lint, helm
        run: yarn helm:lint

      - name: Test
        run: yarn test:coverage

      - name: Test build
        run: yarn build

      - name: Test coverage
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
