name: Build and Push to Quay

on:
  push:
    branches:
      - 'release-v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Increase File Descriptors Limit
        run: ulimit -n 4096

      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build/Containerfile
          push: true
          tags: quay.io/kubev2v/forklift-console-plugin:${GITHUB_REF#refs/heads/}

      - name: Logout from Quay.io
        run: docker logout quay.io
